"""Public package surface for hello_os."""

from .core import (
    BOLTZMANN_CONSTANT,
    GRAVITATIONAL_CONSTANT,
    LIGHT_SPEED,
    MATERIALS,
    Material,
    OptimizationResult,
    RotorDesign,
    RotorMetrics,
    SignalTrace,
    angular_velocity_from_rpm,
    available_materials,
    classify_safety,
    estimate_integration_seconds,
    estimate_rotor_metrics,
    get_material,
    gravitomagnetic_field,
    optimize_rotor,
    quantum_noise,
    simulate_trace,
)

__all__ = [
    "BOLTZMANN_CONSTANT",
    "GRAVITATIONAL_CONSTANT",
    "LIGHT_SPEED",
    "MATERIALS",
    "Material",
    "OptimizationResult",
    "RotorDesign",
    "RotorMetrics",
    "SignalTrace",
    "angular_velocity_from_rpm",
    "available_materials",
    "classify_safety",
    "estimate_integration_seconds",
    "estimate_rotor_metrics",
    "get_material",
    "gravitomagnetic_field",
    "optimize_rotor",
    "quantum_noise",
    "simulate_trace",
]
